[package]
name = "minikv-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
minikv-core = { path = "../minikv-core" }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
colored = "3.0.0"
